export interface IMenuLangSet {
    home: string,
    studies: string,
    skills: string,
    services: string,
    portfolio: string,
    about: string,
    contact: string
}

export interface IFooterLangSet {
    address: string,
    phone: string
}

export interface IHomeLangSet {
    address: string,
    phone: string,
    nationality: string,
    birthday: string,
    driving: string,
    skills: string,
    services: string,
    ingenieur: string,
    txt1: string,
    txt2: string,
    contact: string,
    contacttxt: string
}

export interface IStudiesLangSet {
    address: string,
    phone: string,
    nationality: string,
    birthday: string,
    driving: string,
    skills: string,
    services: string,
    studies: string,
    et1title: string,
    et2title: string,
    et3title: string,
    et4title: string,
    et1: string,
    et1a: string,
    et1b: string,
    et2: string,
    et2a: string,
    et3: string,
    et3a: string,
    et3b: string,
    et3c: string,
    et4: string,
    et4b: string,
    et4c: string,
    et4d: string,
    exp1title: string,
    exp2title: string,
    exp3title: string,
    exp4title: string,
    exp1: string,
    exp1a: string,
    exp1b: string,
    exp1c: string,
    exp1d: string,
    exp1e: string,
    exp2: string,
    exp2a: string,
    exp3: string,
    exp3a: string,
    exp3b: string,
    exp4: string,
    exp4a: string,
    exp4b: string,
}

export interface IContactLangSet {
    // address: string,
    // phone: string,
    // nationality: string,
    // birthday: string,
    // driving: string,
    // skills: string,
    // services: string,
    // studies: string,
    // et1title: string,
    // et2title: string,
    // et3title: string,
    // et4title: string,
    // et1: string,
    // et1a: string,
    // et1b: string,
    // et2: string,
    // et2a: string,
    // et3: string,
    // et3a: string,
    // et3b: string,
    // et3c: string,
    // et4: string,
    // et4b: string,
    // et4c: string,
    // et4d: string,
    // exp1title: string,
    // exp2title: string,
    // exp3title: string,
    // exp4title: string,
    // exp1: string,
    // exp1a: string,
    // exp1b: string,
    // exp1c: string,
    // exp1d: string,
    // exp1e: string,
    // exp2: string,
    // exp2a: string,
    // exp3: string,
    // exp3a: string,
    // exp3b: string,
    // exp4: string,
    // exp4a: string,
    // exp4b: string,
}

export interface ILangSet {
    "menu": IMenuLangSet,
    "footer": IFooterLangSet,
    "home": IHomeLangSet,
    "studies": IStudiesLangSet,
    "contact": IContactLangSet
}

export interface ILang {
    "en": ILangSet,
    "fr": ILangSet
}

export type AllowedLangs = "en" | "fr"

export const LANGS: ILang = {
    "en": {
        "menu": {
            home: "Home",
            studies: "Studies & Experience",
            skills: "Skills",
            services: "Services",
            portfolio: "Portfolio",
            about: "About me",
            contact: "Contact"
        },
        "footer": {
            address: "Address",
            phone: "Phone"
        },
        "home": {
            address: "Address",
            phone: "Phone Number",
            nationality: "Nationality",
            birthday: "Date of birth",
            driving: "Driving",
            skills: "See skills",
            services: "See services",
            ingenieur: "Engineering Student",
            txt1: "I am currently studying computer science at the National Graduate School of Advanced Techniques of Paris (ENSTA Paris), France, top ten among the best highly selective ‘Grandes Ecoles’.",
            txt2: "I am targetting a 6 months internship in the field of cybersecurity during which I should achieve a technical project. This internship would be an opportunity for me to have a first concrete professional experience, in an actual company, which will be decisive in finding my first job.",
            contact: "Contact me now!",
            contacttxt: "If you are interested in any of my skills or services, or if you have any question, feel free to contact me!"
        },
        "studies": {
            address: "Address",
            phone: "Phone Number",
            nationality: "Nationality",
            birthday: "Date of birth",
            driving: "Driving",
            skills: "See skills",
            services: "See services",
            studies: "Studies",
            et1title: "Paris suburbs",
            et2title: "Paris suburbs",
            et3title: "Faidherbe High School",
            et4title: "Madeleine Michelis High School",
            et1: "Anticipated graduation with a french « Diplôme d’Ingénieur Informatique » - top diploma equivalent to a top Honors Master’s Degree in Informatics, with strong informatic engineer training.",
            et1a: "Graduate Major : Achitecture and Security of Information Systems",
            et1b: "Anticipated graduation with a parallel Master in cybersecurity - Telecom Paris",
            et2: "French Baccalauréat in Science with Honors",
            et2a: "I succeeded a scientific french Baccalauréat with honors, acquiring basic knowledge in many scientific fields (Maths, Physics, Computer Science, Biology).",
            et3: "Preparatory Class",
            et3a: "I spent two years of highly intensive undergraduate courses preparing for the competitive entrance examination to very selective French ‘Grandes Ecoles’.",
            et3b: "Very strong background in hard sciences: Mathematics, Physics, Computer Science",
            et3c: "Successfully coped with a very heavy workload of more than 60 weekly hours of classes, tests and lab sessions",
            et4: "to June",
            et4b: "Awarded the B.S in Informatics, Maths and Physics",
            et4c: "Undergraduate Major : General Scientific Knowledge in Informatics (A), Maths and Physics",
            et4d: "Undergraduate Minor : Artificial Intelligence (A) and Genetic Algorithms (A)",
            exp1title: "Orange, Northern Intervention Unit - Amiens",
            exp2title: "TAEP Junior Company - Paris",
            exp3title: "Pierre Bernard Architectural Firm - Amiens",
            exp4title: "Eiffage Public Works - Amiens",
            exp1: "June 2019 - Network Technician",
            exp1a: "I worked among the Northern Intervention Unit, within an international company and an enterprise environment to provide a quality telecommunication service to users on the network. \nSelected contributions:",
            exp1b: "Wrote reports on the activities conducted by technicians",
            exp1c: "Ran tests to check the quality of optical fibre and copper lines",
            exp1d: "Install and solder optical fibre cables",
            exp1e: "Working in this unit was a good opportunity for me to learn business life as well as some technical knowledge of networks in general.",
            exp2: "June 2013 - Public works worker",
            exp2a: "I worked among a worker unit on a couple building sites in order to have a first glance at the business world. I helped workers on very concrete aspects and learnt a lot about workers' working conditions as well.",
            exp3: "June 2014 - Architect in a small firm",
            exp3a: "I joined the work of a small architectural firm and noted the stakes of smaller companies, be it on small or medium scale projects.",
            exp3b: "During this internship I wrote a complete file on a selected architectural building - The Millenium Bridge (London) - and thus I learnt how such projects are conducted and what stakeholders are involved.",
            exp4: "2018/2019 - Treasurer and Quality Manager",
            exp4a: "TAEP is the junior company of ENSTA Paris. Junior companies link students to actual companies which have projects for them.",
            exp4b: "In this company I developped many skills in treasury and project management along with working in a company environment. We also had the opportunity to developped partnerships with other universities including La Sorbonne and Polytechnique.",
        },
        "contact": {

        }
    },
    "fr": {
        "menu": {
            home: "Accueil",
            studies: "Etudes & Experience",
            skills: "Compétences",
            services: "Services",
            portfolio: "Portfolio",
            about: "À propos",
            contact: "Contact"
        },
        "footer": {
            address: "Adresse",
            phone: "Tel"
        },
        "home": {
            address: "Adresse",
            phone: "Telephone",
            nationality: "Nationalité",
            birthday: "Date de naissance",
            driving: "Permis de conduire",
            skills: "Voir compétences",
            services: "Voir services",
            ingenieur: "Ingénieur étudiant",
            txt1: "Je suis actuellement étudiant en informatique à l'Ecole Nationale Supérieure des Techniques Avancées (ENSTA Paris), France, top 10 parmi les Grandes Ecoles d'ingénieurs françaises.",
            txt2: "Je suis à la recherche d'un stage de 6 mois dans le domaine de la cybersécurité au cours duquel je devrais mener un projet technique concret. Ce stage sera pour moi l'opportunité d'avoir une première expérience technique concrète en entreprise, ce qui sera décisif pour la recherche de mon premier emploi.",
            contact: "Contactez-moi!",
            contacttxt: "Si vous êtes intéressé par l'une de mes compétences ou l'un de mes services, ou si vous avez des questions, n'hésitez pas à me contacter!"
        },
        "studies": {
            address: "Adresse",
            phone: "Telephone",
            nationality: "Nationalité",
            birthday: "Date de naissance",
            driving: "Permis de conduire",
            skills: "Voir compétences",
            services: "Voir services",
            studies: "Etudes",
            et1title: "Palaiseau",
            et2title: "Palaiseau",
            et3title: "Lycée Faidherbe",
            et4title: "Lycée Madeleine Michelis",
            et1: "Diplôme d'Ingénieur Informatique anticipé avec des compétences solides en informatique",
            et1a: "Majeure : Achitecture et Sécurité des Systèmes d'Information",
            et1b: "Master en parallèle anticipé en Cybersécurité - Telecom Paris",
            et2: "Baccalauréat Scientifique Mention Très Bien",
            et2a: "J'ai obtenu le baccalauréat avec la mention Très Bien, obtenu ainsi des connaissances de base dans de nombreux domaines scientifiques (Maths, Physique, Informatique, Biologie).",
            et3: "Classe Préparatoire aux Grandes Ecoles",
            et3a: "J'ai travaillé pendant deux ans à la préparation des concours très selectifs d'entrée dans les Grandes Ecoles d'Ingénieur françaises.",
            et3b: "De solides connaissances théorique en sciences dures: Maths, Physique, Informatique",
            et3c: "Quantité de travail exigeante avec 60 heures par semaine de cours, examens et travaux pratiques.",
            et4: "à Juin",
            et4b: "Equivalent Licence L3 en Informatique, Maths et Physique",
            et4c: "Majeure : Tronc commun scientifique en Maths, Physique et Informatique",
            et4d: "Mineure : Intelligence Artificielle et Algorithmes Génétiques",
            exp1title: "Orange, Unité d'Intervention Nord de France - Amiens",
            exp2title: "TAEP Junior Entreprise - Paris",
            exp3title: "Cabinet d'Architectes Pierre Bernard - Amiens",
            exp4title: "Eiffage Travaux Publics - Amiens",
            exp1: "Juin 2019 - Technicien Réseau",
            exp1a: "J'ai travaillé au sein de l'Unité d'Intervention Nord de France, dans une firme d'échelle internationale et dans un environnement d'entreprise pour fournir un service de télécomunication de qualité aux utilisateurs réseau. \nTravail effectué:",
            exp1b: "Rédaction de rapports d'activité sur les tâches réalisées par les techniciens",
            exp1c: "Réalisation de tests pour vérifier la qualité des lignes fibre et cuivre",
            exp1d: "Installation et soudure de fibre optique",
            exp1e: "Travailler au sein de cette unité a été l'opportunité pour moi de découvrir en détail le monde du travail, tout en développant une connaissance technique des réseaux telecom.",
            exp2: "Juin 2013 - Ouvrier Travaux Publics",
            exp2a: "J'ai travaillé au sein d'une équipe d'ouvriers sur quelques chantiers pour avoir un premeir contact avec le monde du travail. J'ai aidé les ouvriers pour certaines de leurs tâches et j'ai également beaucoup appris sur leurs conditions de travail.",
            exp3: "Juin 2014 - Architecte dans un cabinet",
            exp3a: "J'ai participé au travail d'un cabinet d'architectes et ai ainsi pu observer les enjeux des plus petites entreprises, sur des projets de petite et moyenne taille.",
            exp3b: "Durant ce stage, j'ai rédigé un dossier complet au sujet d'un ouvrage d'art de mon choix - Le Millenium Bridge (Londres) - et j'ai ainsi appris comment de tels projets étaient menés et quels collaborateurs y contribuent.",
            exp4: "2018/2019 - Trésorier et Chargé de Qualité",
            exp4a: "TAEP est la Junior Entreprise de l'ENSTA Paris. Les Junior Entreprises mettent en relation les étudiants et les entreprises qui ont des projets à leur proposer.",
            exp4b: "Au sein de cette entreprise, j'ai développé de nombreuses compétences en trésorerie et en gestion de projet, tout en apprenant à travailler dans un contexte d'entrprise. Nous avons également pu développer des partenariats avec les Junior Entreprises d'autres universités parisiennes dont La Sorbonne et Polytechnique.",
        },
        "contact": {

        }
    }
}